added network create function and /24 block instantiation

diff --git a/weave-vlanmgmt b/weave-vlanmgmt
--- a/weave-vlanmgmt
+++ b/weave-vlanmgmt
@@ -4,7 +4,8 @@ set -e
 
 #check for etcdctl in path and bomb if not
 etcdctl -v >/dev/null 2>&1 || { echo >&2 "$0 requires etcdctl but it's not in our path.  Aborting."; exit 1; }
-
+#check for cidr-to-ip.sh
+./cidr-to-ip.sh >/dev/null 2>&1 || { echo >&2 "$0 requires cidr-to-ip.sh but it's not in our path.  Aborting."; exit 1; }
 
 vlan() {
   
@@ -28,10 +29,47 @@ vlan() {
     etcdctl ls /weave/vlans/$1 2>&1 1>/dev/null | grep '100:' | wc -l || true
   }
   
+#returns 0 if network DOESNT exist
   does_network_exist_in_vlan() {
-    etcdctl ls /weave/vlans/$1/network/$2 2>&1/dev/null | grep '100:' | wc -l || true
+    etcdctl ls /weave/vlans/$1/network/$2 2>&1 1>/dev/null | grep '100:' | wc -l || true
   }
-  
+
+#woop networks
+ network_address_to_ips() {
+  # define empty array to hold the ip addresses
+  MYIPARRAY=()
+  # create array containing network address and subnet
+  network=(${1//\// })
+  # split network address by dot
+  iparr=(${network[0]//./ })
+  # check for subnet mask or create subnet mask from CIDR notation
+  if [[ ${network[1]} =~ '.' ]]; then
+    netmaskarr=(${network[1]//./ })
+  else
+    if [[ $((8-${network[1]})) > 0 ]]; then
+      netmaskarr=($((256-2**(8-${network[1]}))) 0 0 0)
+    elif  [[ $((16-${network[1]})) > 0 ]]; then
+      netmaskarr=(255 $((256-2**(16-${network[1]}))) 0 0)
+    elif  [[ $((24-${network[1]})) > 0 ]]; then
+      netmaskarr=(255 255 $((256-2**(24-${network[1]}))) 0)
+    elif [[ $((32-${network[1]})) > 0 ]]; then 
+      netmaskarr=(255 255 255 $((256-2**(32-${network[1]}))))
+    fi
+  fi
+  # correct wrong subnet masks (e.g. 240.192.255.0 to 255.255.255.0)
+  [[ ${netmaskarr[2]} == 255 ]] && netmaskarr[1]=255
+  [[ ${netmaskarr[1]} == 255 ]] && netmaskarr[0]=255
+  # generate list of ip addresses
+  for i in $(seq 0 $((255-${netmaskarr[0]}))); do
+    for j in $(seq 0 $((255-${netmaskarr[1]}))); do
+      for k in $(seq 0 $((255-${netmaskarr[2]}))); do
+        for l in $(seq 1 $((255-${netmaskarr[3]}))); do
+          MYIPARRAY+=( $(( $i+$(( ${iparr[0]}  & ${netmaskarr[0]})) ))"."$(( $j+$(( ${iparr[1]} & ${netmaskarr[1]})) ))"."$(($k+$(( ${iparr[2]} & ${netmaskarr[2]})) ))"."$(($l+$((${iparr[3]} & ${netmaskarr[3]})) )) )
+        done
+      done
+    done
+  done
+}
   cidr2mask() {
     local i mask=""
     local full_octets=$(($1/8))
@@ -121,7 +159,7 @@ vlan() {
         vlan)
           #          VLANEXIST=$(etcdctl ls /weave/vlans/$3 2>&1 | grep 100 || true)
           VLANEXIST=$(does_vlan_exist $3)
-          if [ "$VLANEXIST" -ne 1 ] ; then
+          if [ "$VLANEXIST" == 0 ] ; then
             echo "Sorry - a vlan numbered $3 already exists!"
             exit 1
           else
@@ -143,27 +181,42 @@ vlan() {
             echo "You need 2 params - block in cidr notation and target vlan"
             exit 1
           fi
+	  ADDRESSBLOCK=$(echo $1 | awk -F\/ '{print $1}')
+          CURRCIDR=$(echo $1 | awk -F\/ '{print $2}')
+	  if [ $CURRCIDR != 24 ] ; then
+	     echo "Sorry only supporting /24 blocks right now!"
+	     exit 1
+  	  fi
           echo "Checking if the vlan exists...."
+	  echo "My args are: $*"
+	  echo "I am passing $2 to does_vlan_exist"
           VLANEXIST=$(does_vlan_exist $2)
           if [ $VLANEXIST == 1  ] ; then
             echo "Sorry - vlan $3 doesnt exist!"
             exit 1
           fi
-          NETWORKEXIST=$(does_network_exist_in_vlan $2 $1)
-          if [ $NETWORKEXIST -ne 0 ] ; then
+	  echo "Checking if network exists in target vlan..."
+	  echo "My args are: $*"
+	  echo "I am passing $2 $1 to does_network_exist_in_vlan"
+          NETWORKEXIST=$(does_network_exist_in_vlan $2 $ADDRESSBLOCK)
+	  echo "value of NETWORKEXIST is $NETWORKEXIST"
+          if [ $NETWORKEXIST ==  0 ] ; then
             echo "Sorry - network $1 already exists in vlan $2"
             exit 1
           fi
           echo "I am doing the stuffs"
           echo "Calcumalating...."
+	  network_address_to_ips $1
           ADDRESSBLOCK=$(echo $1 | awk -F\/ '{print $1}')
           CURRCIDR=$(echo $1 | awk -F \/ '{print $2}')
           NETMASK=$(cidr2mask $CURRCIDR)
-          #	TARGETVLAN=$(etcdctl get /weave/vlans/namemap/$2 2>&1 | grep 100 || true)
           TARGETVLAN=$(get_vlan_name $2)
           echo "Target VLAN: $2"
           echo "Addressblock=$ADDRESSBLOCK"
           echo "Netmask=$NETMASK"
+	  for i in ${MYIPARRAY[*]} ; do
+	    echo $i
+          done
         ;;
         *)
           echo "Invalid selection"
